development:
  adapter: mysql2
  encoding: utf8
  database: myweightworld_development
  username: root
  password: dl6cd1357
  host: localhost
  pool: 5
  timeout: 5000
  
test:
  adapter: mysql2
  encoding: utf8
  database: myweightworld_test
  username: root
  password: dl6cd1357
  host: localhost
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8
  database: myweightworld_production
  username: root
  password: dl6cd1357
  host: localhost
  pool: 5
  timeout: 5000
