development:
  adapter: mysql
  encoding: utf8
  database: myweightworld_development
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  
test:
  adapter: mysql
  encoding: utf8
  database: myweightworld_test
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000