development:
  adapter: mysql2
  encoding: utf8
  database: myweightworld_development
  username: root
  password: ubuntu
  host: localhost
  pool: 5
  timeout: 5000
  
test:
  adapter: mysql2
  encoding: utf8
  database: myweightworld_test
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8
  database: myweightworld_production
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
