
development:
  adapter: mysql
  encoding: utf8
  database: so_church_development
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000

test: &TEST
  adapter: mysql
  encoding: utf8
  database: so_church_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000

cucumber: &CUCUMBER
  <<: *TEST
culerity:
  <<: *CUCUMBER