module VendorsHelper

def us_states
    [
		['Other', 'Other'],
      ['Alabama', 'Alabama'],
      ['Alaska', 'Alaska'],
      ['Arizona', 'Arizona'],
      ['Arkansas', 'Arkansas'],
      ['California', 'Arkansas'],
      ['Colorado', 'Colorado'],
      ['Connecticut', 'Connecticut'],
      ['Delaware', 'Delaware'],
      ['District of Columbia', 'District of Columbia'],
      ['Florida', 'Florida'],
      ['Georgia', 'Georgia'],
      ['Hawaii', 'Hawaii'],
      ['Idaho', 'Idaho'],
      ['Illinois', 'Illinois'],
      ['Indiana', 'Indiana'],
      ['Iowa', 'Iowa'],
      ['Kansas', 'Kansas'],
      ['Kentucky', 'Kentucky'],
      ['Louisiana', 'Louisiana'],
      ['Maine', 'Maine'],
      ['Maryland', 'Maryland'],
      ['Massachusetts', 'Massachusetts'],
      ['Michigan', 'Michigan'],
      ['Minnesota', 'Minnesota'],
      ['Mississippi', 'Mississippi'],
      ['Missouri', 'Missouri'],
      ['Montana', 'Montana'],
      ['Nebraska', 'Nebraska'],
      ['Nevada', 'Nevada'],
      ['New Hampshire', 'New Hampshire'],
      ['New Jersey', 'New Jersey'],
      ['New Mexico', 'New Mexico'],
      ['New York', 'New York'],
      ['North Carolina', 'North Carolina'],
      ['North Dakota', 'North Dakota'],
      ['Ohio', 'Ohio'],
      ['Oklahoma', 'Oklahoma'],
      ['Oregon', 'Oregon'],
      ['Pennsylvania', 'Pennsylvania'],
      ['Puerto Rico', 'Puerto Rico'],
      ['Rhode Island', 'Rhode Island'],
      ['South Carolina', 'South Carolina'],
      ['South Dakota', 'South Dakota'],
      ['Tennessee', 'Tennessee'],
      ['Texas', 'Texas'],
      ['Utah', 'Utah'],
      ['Vermont', 'Vermont'],
      ['Virginia', 'Virginia'],
      ['Washington', 'Washington'],
      ['West Virginia', 'West Virginia'],
      ['Wisconsin', 'Wisconsin'],
      ['Wyoming', 'Wyoming']

    ]
end

def countries
[
                    ['United States', 'United States'],
      ['Afghanistan','Afghanistan'],
                    ['Aland Islands', 'Aland Islands'],
                    ['Albania',   'Albania'],
                    ['Algeria',   'Algeria'],
                    ['Samoa',   'American Samoa'],
                    ['Andorra',   'Andorra'],
                    ['Angola',   'Angola'],
                    ['Anguilla',   'Anguilla'],
                    ['Antarctica',   'Antarctica'],
                    ['Antigua and Barbuda',   'Antigua and Barbuda'],
                    ['Argentina',   'Argentina'],
                    ['Armenia',   'Armenia'],
                    ['Aruba',   'Aruba'],
                    ['Australia',   'Australia'],
                    ['Austria',   'Austria'],
                    ['Azerbaijan',   'Azerbaijan'],
                    ['Bahamas',   'Bahamas'],
                    ['Bahrain',   'Bahrain'],
                    ['Bangladesh',   'Bangladesh'],
                    ['Barbados',   'Barbados'],
                    ['Belarus',   'Belarus'],
                    ['Belgium',   'Belgium'],
                    ['Belize',   'Belize'],
                    ['Benin',   'Benin'],
                    ['Bermuda',   'Bermuda'],
                    ['Bhutan',   'Bhutan'],
                    ['Bolivia',   'Bolivia'],
                    ['Bosnia and Herzegovina',   'Bosnia and Herzegovina'],
                    ['Botswana',   'Botswana'],
                    ['Island',   'Bouvet Island'],
                    ['Brazil',   'Brazil'],
                    ['British Indian Ocean Territory',   'British Indian Ocean Territory'],
                    ['British Virgin Islands',   'British Virgin Islands'],
                    ['Brunei',   'Brunei'],
                    ['Bulgaria',   'Bulgaria'],
                    ['Burkina Faso',   'Burkina Faso'],
                    ['Burundi',   'Burundi'],
                    ['Cambodia',   'Cambodia'],
                    ['Cameroon',   'Cameroon'],
                    ['Canada',   'Canada'],
                    ['Cape Verde',   'Cape Verde'],
                    ['Cayman Islands',   'Cayman Islands'],
                    ['Central African Republic',   'Central African Republic'],
                    ['Chad',   'Chad'],
                    ['Chile',   'Chile'],
                    ['China',   'China'],
                    ['Christmas Island',   'Christmas Island'],
                    ['Cocos (Keeling) Islands',   'Cocos (Keeling) Islands'],
                    ['Colombia',   'Colombia'],
                    ['Union of the Comoros',   'Union of the Comoros'],
                    ['Congo',   'Congo'],
                    ['Cook Islands',   'Cook Islands'],
                    ['Costa Rica',   'Costa Rica'],
                    ['Croatia',   'Croatia'],
                    ['Cuba',   'Cuba'],
                    ['Cyprus',   'Cyprus'],
                    ['Czech Republic',   'Czech Republic'],
                    ['Democratic Republic of Congo',   'Democratic Republic of Congo'],
                    ['Denmark',   'Denmark'],
                    ['Disputed Territory',   'Disputed Territory'],
                    ['Djibouti',   'Djibouti'],
                    ['Dominica',   'Dominica'],
                    ['Dominican Republic',   'Dominican Republic'],
                    ['East Timor',   'East Timor'],
                    ['Ecuador',   'Ecuador'],
                    ['Egypt',   'Egypt'],
                    ['El Salvador',   'El Salvador'],
                    ['Equatorial Guinea',   'Equatorial Guinea'],
                    ['Eritrea',   'Eritrea'],
                    ['Estonia',   'Estonia'],
                    ['Ethiopia',   'Ethiopia'],
                    ['Falkland',   'Falkland Islands'],
                    ['Faroe Islands',   'Faroe Islands'],
                    ['Federated States of Micronesia',   'Federated States of Micronesia'],
                    ['Fiji',   'Fiji'],
                    ['Finland',   'Finland'],
                    ['France',   'France'],
                    ['French Guyana',   'French Guyana'],
                    ['French Polynesia',   'French Polynesia'],
                    ['French Southern Territories',   'French Southern Territories'],
                    ['Gabon',   'Gabon'],
                    ['Gambia',   'Gambia'],
                    ['Georgia',   'Georgia'],
                    ['Germany',   'Germany'],
                    ['Ghana',   'Ghana'],
                    ['Gibraltar',   'Gibraltar'],
                    ['Greece',   'Greece'],
                    ['Greenland',   'Greenland'],
                    ['Grenada',   'Grenada'],
                    ['Guadeloupe',   'Guadeloupe'],
                    ['Guam',   'Guam'],
                    ['Guatemala',   'Guatemala'],
                    ['Guinea',   'Guinea'],
                    ['Guinea-Bissau',   'Guinea-Bissau'],
                    ['Guyana',   'Guyana'],
                    ['Haiti',   'Haiti'],
                    ['Heard Island and McDonald Islands',   'Heard Island and McDonald Islands'],
                    ['Honduras',   'Honduras'],
                    ['Hong Kong',   'Hong Kong'],
                    ['Hungary',   'Hungary'],
                    ['Iceland',   'Iceland'],
                    ['India',   'India'],
                    ['Indonesia',   'Indonesia'],
                    ['Iran',   'Iran'],
                    ['Iraq',   'Iraq'],
                    ['Iraq-Saudi Arabia Neutral Zone',   'Iraq-Saudi Arabia Neutral Zone'],
                    ['Ireland',   'Ireland'],
                    ['Israel',   'Israel'],
                    ['Italy',   'Italy'],
                    ['Ivory Coast',   'Ivory Coast'],
                    ['Jamaica',   'Jamaica'],
                    ['Japan',   'Japan'],
                    ['Jordan',   'Jordan'],
                    ['Kazakhstan',   'Kazakhstan'],
                    ['Kenya',   'Kenya'],
                    ['Kiribati',   'Kiribati'],
                    ['Kuwait',   'Kuwait'],
                    ['Kyrgyz Republic',   'Kyrgyz Republic'],
                    ['Laos',   'Laos'],
                    ['Latvia',   'Latvia'],
                    ['Lebanon',   'Lebanon'],
                    ['Lesotho',   'Lesotho'],
                    ['Liberia',   'Liberia'],
                    ['Libya',   'Libya'],
                    ['Liechtenstein',   'Liechtenstein'],
                    ['Lithuania',   'Lithuania'],
                    ['Luxembourg',   'Luxembourg'],
                    ['Macau',   'Macau'],
                    ['Macedonia',   'Macedonia'],
                    ['Madagascar',   'Madagascar'],
                    ['Malawi',   'Malawi'],
                    ['Malaysia',   'Malaysia'],
                    ['Maldives',   'Maldives'],
                    ['Mali',   'Mali'],
                    ['Malta',   'Malta'],
                    ['Marshall Islands',   'Marshall Islands'],
                    ['Martinique',   'Martinique'],
                    ['Mauritania',   'Mauritania'],
                    ['Mauritius',   'Mauritius'],
                    ['Mayotte',   'Mayotte'],
                    ['Mexico',   'Mexico'],
                    ['Moldova',   'Moldova'],
                    ['Monaco',   'Monaco'],
                    ['Mongolia',   'Mongolia'],
                    ['Montserrat',   'Montserrat'],
                    ['Morocco',   'Morocco'],
                    ['Mozambique',   'Mozambique'],
                    ['Myanmar',   'Myanmar'],
                    ['Namibia',   'Namibia'],
                    ['Nauru',   'Nauru'],
                    ['Nepal',   'Nepal'],
                    ['Netherlands',   'Netherlands'],
                    ['Netherlands Antilles',   'Netherlands Antilles'],
                    ['New Caledonia',   'New Caledonia'],
                    ['New Zealand',   'New Zealand'],
                    ['Nicaragua',   'Nicaragua'],
                    ['Niger',   'Niger'],
                    ['Nigeria',   'Nigeria'],
                    ['Niue',   'Niue'],
                    ['Norfolk Island',   'Norfolk Island'],
                    ['North Korea',   'North Korea'],
                    ['Northern Mariana Islands',   'Northern Mariana Islands'],
                    ['Norway',   'Norway'],
                    ['Oman',   'Oman'],
                    ['Pakistan',   'Pakistan'],
                    ['Palau',   'Palau'],
                    ['Palestinian Territories',   'Palestinian Territories'],
                    ['Panama',   'Panama'],
                    ['Papua New Guinea',   'Papua New Guinea'],
                    ['Paraguay',   'Paraguay'],
                    ['Peru',   'Peru'],
                    ['Philippines',   'Philippines'],
                    ['Pitcairn Islands',   'Pitcairn Islands'],
                    ['Poland',   'Poland'],
                    ['Portugal',   'Portugal'],
                    ['Puerto Rico',   'Puerto Rico'],
                    ['Qatar',   'Qatar'],
                    ['Reunion',   'Reunion'],
                    ['Romania',   'Romania'],
                    ['Russia',   'Russia'],
                    ['Rwanda',   'Rwanda'],
                    ['Saint Helena and Dependencies',   'Saint Helena and Dependencies'],
                    ['Saint Kitts & Nevis',   'Saint Kitts & Nevis'],
                    ['Saint Lucia',   'Saint Lucia'],
                    ['Saint Pierre and Miquelon',   'Saint Pierre and Miquelon'],
                    ['Saint Vincent and the Grenadines',   'Saint Vincent and the Grenadines'],
                    ['Samoa',   'Samoa'],
                    ['San Marino',   'San Marino'],
                    ['Sao Tome and Principe',   'Sao Tome and Principe'],
                    ['Saudi Arabia',   'Saudi Arabia'],
                    ['Senegal',   'Senegal'],
                    ['Seychelles',   'Seychelles'],
                    ['Sierra Leone',   'Sierra Leone'],
                    ['Singapore',   'Singapore'],
                    ['Slovakia',   'Slovakia'],
                    ['Slovenia',   'Slovenia'],
                    ['Solomon Islands',   'Solomon Islands'],
                    ['Somalia',   'Somalia'],
                    ['South Africa',   'South Africa'],
                    ['South Georgia and the South Sandwich Islands',   'South Georgia and the South Sandwich Islands'],
                    ['South Korea',   'South Korea'],
                    ['Spain',   'Spain'],
                    ['Spratly Islands',   'Spratly Islands'],
                    ['Sri Lanka',   'Sri Lanka'],
                    ['Sudan',   'Sudan'],
                    ['Suriname',   'Suriname'],
                    ['Svalbard and Jan Mayen Islands',   'Svalbard and Jan Mayen Islands'],
                    ['Swaziland',   'Swaziland'],
                    ['Sweden',   'Sweden'],
                    ['Switzerland',   'Switzerland'],
                    ['Syria',   'Syria'],
                    ['Taiwan',   'Taiwan'],
                    ['Tajikistan',   'Tajikistan'],
                    ['Tanzania',   'Tanzania'],
                    ['Thailand',   'Thailand'],
                    ['Togo',   'Togo'],
                    ['Tokelau',   'Tokelau'],
                    ['Tonga',   'Tonga'],
                    ['Trinidad and Tobago',   'Trinidad and Tobago'],
                    ['Tunisia',   'Tunisia'],
                    ['Turkey',   'Turkey'],
                    ['Turkmenistan',   'Turkmenistan'],
                    ['Turks and Caicos Islands',   'Turks and Caicos Islands'],
                    ['Tuvalu',   'Tuvalu'],
                    ['Uganda',   'Uganda'],
                    ['Ukraine',   'Ukraine'],
                    ['United Arab Emirates',   'United Arab Emirates'],
                    ['United Kingdom',   'United Kingdom'],
                    ['United States Minor Outlying Islands',   'United States Minor Outlying Islands'],
                    ['Uruguay',   'Uruguay'],
                    ['US Virgin Islands',   'US Virgin Islands'],
                    ['Uzbekistan',   'Uzbekistan'],
                    ['Vanuatu',   'Vanuatu'],
                    ['Vatican City',   'Vatican City'],
                    ['Venezuela',   'Venezuela'],
                    ['Vietnam',   'Vietnam'],
                    ['Wallis and Futuna Islands',   'Wallis and Futuna Islands'],
                    ['Western Sahara',   'Western Sahara'],
                    ['Yemen',   'Yemen'],
                    ['Zambia',   'Zambia'],
                    ['Zimbabwe',   'Zimbabwe'],
                    ['Serbia',   'Serbia'],
                    ['Montenegro',   'Montenegro']

	]
	end

  def five_hundred_calorie_deficit(user)
    if user.bmr
      user.bmr - 500
    else
      0
    end
  end
  
  def one_thousand_calorie_deficit(user)
    if user.bmr
      user.bmr - 1000
    else
      0
    end
  end
  
  def pounds_to_lose(user)
    if user.desired_weight
      user.weight - user.desired_weight
    else
      0
    end
  end
  
  def days_to_goal(user, daily_deficity)
    total_calories_to_lose = pounds_to_lose(@user) * 3500
    (total_calories_to_lose / daily_deficity).round
  end

end
